# Use Node.js 16 as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy only the 'ui' directory and its contents to the working directory inside the container
COPY ./ui /app/ui

# Set the working directory to the 'ui' folder where your package.json is located
WORKDIR /app/ui

# Install dependencies
RUN npm install

# Expose the port 4200 for Angular app
EXPOSE 4200

# Start the application with the host binding
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--disable-host-check"]
